In [1]:
# import dependencies
import pandas as pd

In [9]:
df = pd.read_csv('C:\\Users\\skill\\Play-code\\hospital-operations-analysis\\RAW_DATA\\Hospital Operations(Sheet1).csv')

In [11]:
df.head()

,patient_id,visit_id,age,gender,admission_date,discharge_date,department,diagnosis_category,visit_type,doctor_id,wait_time_minutes,treatment_cost,insurance_type,appointment_status,readmitted_30_days,outcome_status,bed_assigned,city,admission_source
0,P02256,V000001,58,Female,2025-05-29,2025-05-29,Cardiology,Cardiac,Outpatient,DR0094,39,2592.97,Government,Attended,No,Recovered,No,Jeddah,Walk-in
1,P03204,V000002,66,Male,2025-06-21,2025-06-24,General Medicine,Gastro,Inpatient,DR0176,54,5017.56,Self-Pay,Cancelled,No,Recovered,Yes,Riyadh,Walk-in
2,P03007,V000003,90,Female,2024-09-20,2024-09-20,Emergency,Injury,Outpatient,DR0111,60,3398.95,Self-Pay,Attended,Yes,Under Observation,No,Riyadh,Emergency Transfer
3,P00592,V000004,49,Male,2025-04-13,2025-04-19,ICU,Cardiac,Inpatient,DR0184,11,15008.39,Government,Attended,No,Referred,Yes,Mecca,Emergency Transfer
4,P00572,V000005,22,Male,2024-02-21,2024-02-21,General Medicine,Injury,Outpatient,DR0167,77,1735.48,Government,Attended,Yes,Recovered,No,Mecca,Walk-in

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          10000 non-null  object
 1   visit_id            10000 non-null  object
 2   age                 10000 non-null  int64
 3   gender              10000 non-null  object
 4   admission_date      10000 non-null  datetime64[ns]
 5   discharge_date      10000 non-null  datetime64[ns]
 6   department          10000 non-null  object
 7   diagnosis_category  10000 non-null  object
 8   visit_type          10000 non-null  object
 9   doctor_id           10000 non-null  object
 10  wait_time_minutes   10000 non-null  int64
 11  treatment_cost      10000 non-null  float64
 12  insurance_type      10000 non-null  object
 13  appointment_status  10000 non-null  object
 14  readmitted_30_days  10000 non-null  object
 15  outcome_status      10000 non-null  object
 16  bed_assigned        10000 non-null  object
 17  city                10000 non-null  object
 18  admission_source    10000 non-null  object
 19  length_of_stay      10000 non-null  int64
dtypes: datetime64[ns](2), float64(1), int64(3), object(14)
memory usage: 1.5+ MB

In [13]:
df["admission_date"] = pd.to_datetime(df["admission_date"])
df["discharge_date"] = pd.to_datetime(df["discharge_date"])
df["length_of_stay"] = (df["discharge_date"] - df["admission_date"]).dt.days

In [15]:
df = df[df["length_of_stay"] >= 0]

In [16]:
df.shape

(10000, 20)

In [19]:
df.columns

Index(['patient_id', 'visit_id', 'age', 'gender', 'admission_date',
       'discharge_date', 'department', 'diagnosis_category', 'visit_type',
       'doctor_id', 'wait_time_minutes', 'treatment_cost', 'insurance_type',
       'appointment_status', 'readmitted_30_days', 'outcome_status',
       'bed_assigned', 'city', 'admission_source', 'length_of_stay'],
      dtype='object')

In [18]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [20]:
df.isnull().sum()

patient_id            0
visit_id              0
age                   0
gender                0
admission_date        0
discharge_date        0
department            0
diagnosis_category    0
visit_type            0
doctor_id             0
wait_time_minutes     0
treatment_cost        0
insurance_type        0
appointment_status    0
readmitted_30_days    0
outcome_status        0
bed_assigned          0
city                  0
admission_source      0
length_of_stay        0
dtype: int64

In [21]:
df = df.drop_duplicates()

In [22]:

!pip install mysql-connector-python sqlalchemy

Requirement already satisfied: mysql-connector-python in c:\users\skill\anaconda3\lib\site-packages (9.5.0)
Requirement already satisfied: sqlalchemy in c:\users\skill\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\skill\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\skill\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)

In [23]:
import mysql.connector
from sqlalchemy import create_engine

try:
    db = mysql.connector.connect(
        host="localhost",
        username="root",
        password="password",
        database="healthcare_dep"
    )
    print("Connection successful!")
except mysql.connector.Error as err:
    print(f"Error: {err}")

Connection successful!

In [24]:
engine = create_engine('mysql+mysqlconnector://root:password@localhost/healthcare_dep')
    
    # Write DataFrame to MySQL
table_name = "hospital_data"
df.to_sql(table_name, con=engine, if_exists='replace', index=False)

10000

In [25]:
# Read back sample
pd.read_sql("SELECT * FROM hospital_data LIMIT 10;", engine)

,patient_id,visit_id,age,gender,admission_date,discharge_date,department,diagnosis_category,visit_type,doctor_id,wait_time_minutes,treatment_cost,insurance_type,appointment_status,readmitted_30_days,outcome_status,bed_assigned,city,admission_source,length_of_stay
0,P02256,V000001,58,Female,2025-05-29,2025-05-29,Cardiology,Cardiac,Outpatient,DR0094,39,2592.97,Government,Attended,No,Recovered,No,Jeddah,Walk-in,0
1,P03204,V000002,66,Male,2025-06-21,2025-06-24,General Medicine,Gastro,Inpatient,DR0176,54,5017.56,Self-Pay,Cancelled,No,Recovered,Yes,Riyadh,Walk-in,3
2,P03007,V000003,90,Female,2024-09-20,2024-09-20,Emergency,Injury,Outpatient,DR0111,60,3398.95,Self-Pay,Attended,Yes,Under Observation,No,Riyadh,Emergency Transfer,0
3,P00592,V000004,49,Male,2025-04-13,2025-04-19,ICU,Cardiac,Inpatient,DR0184,11,15008.39,Government,Attended,No,Referred,Yes,Mecca,Emergency Transfer,6
4,P00572,V000005,22,Male,2024-02-21,2024-02-21,General Medicine,Injury,Outpatient,DR0167,77,1735.48,Government,Attended,Yes,Recovered,No,Mecca,Walk-in,0
5,P01078,V000006,39,Male,2025-12-09,2025-12-09,General Medicine,Injury,Outpatient,DR0101,15,1432.22,Government,Attended,No,Recovered,No,Mecca,Referral,0
6,P01428,V000007,77,Male,2025-01-24,2025-01-24,Emergency,Hypertension,Outpatient,DR0169,77,1822.42,Self-Pay,Attended,No,Under Observation,No,Riyadh,Emergency Transfer,0
7,P01618,V000008,86,Female,2024-06-03,2024-06-03,Cardiology,Diabetes,Outpatient,DR0176,20,5726.15,Private,No Show,No,Recovered,No,Dammam,Referral,0
8,P02712,V000009,76,Female,2025-01-11,2025-01-26,General Medicine,Infection,Inpatient,DR0156,48,1346.97,Government,No Show,No,Recovered,Yes,Riyadh,Referral,15
9,P00242,V000010,75,Male,2024-08-01,2024-08-04,General Medicine,Gastro,Inpatient,DR0002,5,3243.58,Private,Attended,No,Recovered,Yes,Riyadh,Emergency Transfer,3